package com.healtouch.model;

public enum Permission {
  PATIENT_VIEW,
  PATIENT_EDIT,
  TREATMENT_CREATE,
  BILL_CHARGE,
  DEPOSIT_RECHARGE,
  DEPOSIT_REFUND,
  BILL_REFUND,
  REPORT_VIEW,
  SYSTEM_MANAGE,
  DISCOUNT_APPLY
}
